PojisteniMVC/PojisteniMVC/Areas/Admin/Controllers/PojistenyController.cs
using Microsoft.AspNetCore.Mvc;
using PojisteniMVC.DataAccess.Repository.IRepository;
using PojisteniMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PojisteniMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PojistenyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public PojistenyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id) //id jen v případě update/edit
        {
            Pojisteny pojisteny = new Pojisteny();
            if(id == null) //jde o create
            {
                return View(pojisteny);
            }
            //jde o update/edit
            pojisteny = _unitOfWork.Pojisteny.Get(id.GetValueOrDefault());
            if (pojisteny == null)
            {
                return NotFound();
            }
            return View(pojisteny);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Pojisteny pojisteny)
        {
            if (ModelState.IsValid)
            {
                if (pojisteny.PojistenyId == 0)
                {
                    _unitOfWork.Pojisteny.Add(pojisteny);
                }
                else
                {
                    _unitOfWork.Pojisteny.Update(pojisteny);
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index)); //nepoužívat "magic string"
            }
            return View(pojisteny);
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll() //vrátí všechny pojištěné v JSON formátu
        {
            var allObj = _unitOfWork.Pojisteny.GetAll();
            return Json(new { data = allObj });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitOfWork.Pojisteny.Get(id);
            if(objFromDb == null)
            {
                return Json(new { success = false, message = "Chyba při mazání" });
            }
            _unitOfWork.Pojisteny.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Odstranění proběhlo úspěšně" });
        }

        #endregion
    }
}

PojisteniMVC/PojisteniMVC/Areas/Customer/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PojisteniMVC.Models;
using PojisteniMVC.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PojisteniMVC.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PojisteniMVC/PojisteniMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PojisteniMVC.Models;
using PojisteniMVC.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PojisteniMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PojisteniMVC/PojisteniMVC/Areas/Admin/Views/Pojisteny/Index.cshtml
@{
    ViewData["Title"] = "Pojištěné osoby";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<div class="row">
    <div class="col-6">
        <h2 class="text-primary">Pojištěné osoby</h2>
    </div>
    <div class="col-6 text-right text-white">
        <a class="btn btn-primary" asp-action="Upsert"><i class="fas fa-plus"></i> &nbsp; Nový pojištěný</a>
    </div>
</div>

<br />
<div class="p-4 border rounded"> 
    <table id="tblData" class="table table-striped table-bordered" style="width:100%">
        <thead class="thead-dark">
            <tr class="table-info"> <!--sloupce musí ladit s Modelem a Jsonem-->
                <th>Jméno</th>
                <th>Příjmení</th>
                <th>Adresa</th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>

@section Scripts{
    <script src="~/js/pojisteny.js"></script>
 }  

PojisteniMVC/PojisteniMVC/Areas/Admin/Views/Pojisteny/Upsert.cshtml
@model PojisteniMVC.Models.Pojisteny
<!--vychází return (u dané metody v Controlleru) - co vrací?!-->
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var title = "Vytvořit záznam";
    ViewData["Title"] = title;
}

<form method="post">
    <div class="row p-3 border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @if (Model.PojistenyId != 0)
        {
            title = "Upravit záznam";
        }
        <div class="col-12 border-bottom">
            <h2 class="text-primary">@title</h2>
        </div>
        <div class="col-8 pt-4">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Jmeno"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Jmeno" class="form-control" />
                    <span asp-validation-for="Jmeno" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Prijmeni"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Prijmeni" class="form-control" />
                    <span asp-validation-for="Prijmeni" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Adresa"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Adresa" class="form-control" />
                    <span asp-validation-for="Adresa" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-8 offset-4">
                    @if (Model.PojistenyId != 0)
                    {
                        <partial name="_EditAndBackToListButton" model="Model.PojistenyId" />
                    }
                    else
                    {
                        <partial name="_CreateAndBackToListButton" />
                    }
                </div>
            </div>
        </div>
    </div>
</form>



@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

PojisteniMVC/PojisteniMVC/Areas/Customer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Pojištění MVC";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PojisteniMVC/PojisteniMVC/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Vytvořit</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Zpět</a>
    </div>
</div>

PojisteniMVC/PojisteniMVC/Views/Shared/_EditAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model">Upravit</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Zpět</a>
    </div>
</div>

PojisteniMVC/PojisteniMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pojištění MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Správa obsahu
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Pojisteny" asp-action="Index">Pojištěné osoby</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white btn-primary">
        <div class="container">
            &copy; 2021 - Pojištění MVC - <a class="text-info" href="https://www.itnetwork.cz/prace-a-podnikani-v-it/rekvalifikacni-kurzy/rekvalifikacni-kurzy-csharp-net/" target="_blank">rekvalifikační projekt</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/a3bc74e4a9.js" crossorigin="anonymous"></script> <!--můj vlastní kód-->
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>